apiVersion: v1
kind: Service
metadata:
  name: space-engineers
  namespace: games
spec:
  type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: space-engineers
  ports:
    - port: 80
      protocol: TCP
      name: fb-http
      targetPort: 80
    - port: 8080
      protocol: TCP
      name: nginx-http
      targetPort: 8080
    - port: 27016
      protocol: UDP
      name: game-data
      targetPort: 27016
