apiVersion: v1
kind: ConfigMap
metadata:
  name: tyz-social-web-templates
  namespace: personal
stringData:
  # ripped from the app, if this changes in the build it must be manually updated
  index.tmpl: |
    {{- /*
    // GoToSocial
    // Copyright (C) GoToSocial Authors admin@gotosocial.org
    // SPDX-License-Identifier: AGPL-3.0-or-later
    //
    // This program is free software: you can redistribute it and/or modify
    // it under the terms of the GNU Affero General Public License as published by
    // the Free Software Foundation, either version 3 of the License, or
    // (at your option) any later version.
    //
    // This program is distributed in the hope that it will be useful,
    // but WITHOUT ANY WARRANTY; without even the implied warranty of
    // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    // GNU Affero General Public License for more details.
    //
    // You should have received a copy of the GNU Affero General Public License
    // along with this program.  If not, see <http://www.gnu.org/licenses/>.
    */ -}}

    {{ template "header.tmpl" .}}
    <section class="excerpt-top">
      home to <span class="count">{{.instance.Stats.user_count}}</span> users
        who posted <span class="count">{{.instance.Stats.status_count}}</span> statuses,
        federating with  <span class="count">{{.instance.Stats.domain_count}}</span> other instances.
    </section>
    <main class="lightgray">
      <section>
        <div className="short-description">
          {{.instance.ShortDescription |noescape}}
        </div>
      </section>
      <section class="apps">
        <p>
          tyz.social does not provide its own webclient, but implements the Mastodon client API.
          You can use this server through a variety of other clients:
        </p>
        <div class="applist">
          <div class="entry">
            <svg role="img" aria-labelledby="phanpyTitle phanpyDesc" class="logo redraw" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 146 120">
              <title id="phanpyTitle">The Phanpy logo</title>
              <desc id="phanpyDesc">A waving flag</desc>
              <path fill="#a4bff7" d="M37.774 11.471c14.639 3.752 19.034 16.557 15.889 31.304-.696 3.261-2.563 6.661-6.356 8.693-3.204 1.717-8.07 2.537-15.338.55l-9.634-2.404C11.651 46.992 8.378 38.733 10.027 31.823c3.627-15.201 15.543-23.48 27.747-20.352Z"/>
              <path fill="#d8e7fe" d="M36.76 15.429c12.289 3.15 15.547 14.114 12.907 26.493-.947 4.44-4.937 9.365-16.664 6.143l-9.684-2.417c-7.854-1.923-10.53-7.8-9.318-12.877 3.016-12.639 12.611-19.943 22.759-17.342Z"/>
              <path fill="#6081e6" d="M27.471 24.991c-1.457-.698-7.229 3.213-7.663 8.926-.182 2.39 4.55 3.237 5.071-.169.725-4.743 3.715-8.218 2.592-8.757Zm10.746 2.005c-2.083.327-.382 5.901-.595 10.727-.123 2.8 4.388 3.464 4.703 2.011 1.098-5.073-2.066-13.058-4.108-12.738Z"/>
            </svg>
            <div>
              <h2>Phanpy</h2>
              <p>Phanpy is a web client for tyz.social</p>
              <a href="https://web.tyz.social/" target="_blank" rel="noopener">Use Phanpy</a>
            </div>
          </div>
          <div class="entry">
            <img class="logo" src="/assets/tusky.svg" alt="The Tusky mascot, a cartoon elephant tooting happily"/>
            <div>
              <h2>Tusky</h2>
              <p>Tusky is a lightweight mobile client for Android.</p>
              <a href="https://tusky.app" target="_blank" rel="noopener">Get Tusky</a>
            </div>
          </div>
          <div class="entry">
            <img class="logo" src="/assets/feditext.svg" alt="The Feditext logo, the characters ft at a slight angle">
            <div>
              <h2>Feditext</h2>
              <p>Feditext (beta) is a beautiful client for iOS, iPadOS and macOS.</p>
              <a href="https://fedi.software/@Feditext" target="_blank" rel="noopener">Get Feditext</a>
            </div>
          </div>
          <div class="entry">
            <img class="logo" src="/assets/mastodon.svg" alt="The Mastodon logo, the character M in a speech bubble">
            <div>
              <h2>More clients</h2>
              <p>Or try one of the clients listed on the official Mastodon page.</p>
              <a href="https://joinmastodon.org/apps" target="_blank" rel="noopener">Get Mastodon apps</a>
            </div>
          </div>
        </div>
      </section>
    </main>
    {{ template "footer.tmpl" .}}
