apiVersion: apps/v1
kind: Deployment
metadata:
  name: evobot
  namespace: personal
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evobot
  template:
    metadata:
      labels:
        app: evobot
    spec:
      containers:
        - name: evobot
          image: eritislami/evobot:2.6.1
          envFrom:
            - secretRef:
                name: evobot
          resources:
            requests:
              cpu: "50m"
            limits:
              memory: "512Mi"
      imagePullSecrets:
        - name: docker-hub
