apiVersion: v1
kind: Service
metadata:
  name: motioneye
spec:
  # type: LoadBalancer
  type: NodePort
  selector:
    app: motioneye
  ports:
    - name: http-motioneye
      protocol: TCP
      port: 80
      targetPort: 8765
    # - name: tcp-stream1
    #   protocol: TCP
    #   port: 9081
    #   targetPort: 9081
    # - name: tcp-stream2
    #   protocol: TCP
    #   port: 9082
    #   targetPort: 9082
    # - name: tcp-stream3
    #   protocol: TCP
    #   port: 9083
    #   targetPort: 9083
    # - name: tcp-stream4
    #   protocol: TCP
    #   port: 9084
    #   targetPort: 9084
