apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: valheim-server
  namespace: games
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "false"
    nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
  labels:
    use-cloudflare-dns-solver: "true"
spec:
  tls:
    - hosts:
        - "valheim.${game_domain}"
        - "map.valheim.${game_domain}"
        - "supervisor.valheim.${game_domain}"
        - "files.valheim.${game_domain}"
      secretName: valheim.${game_domain}-multi-tls
  rules:
    - host: valheim.${game_domain}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: valheim-server-tcp
                port:
                  number: 80
    - host: map.valheim.${game_domain}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: valheim-server-tcp
                port:
                  number: 3000
    - host: supervisor.valheim.${game_domain}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: valheim-server-tcp
                port:
                  number: 9001
    - host: files.valheim.${game_domain}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: valheim-server-tcp
                port:
                  number: 80
