apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-iscsi-db-config
  namespace: personal
data:
  tuning.cnf: |
    # https://help.nextcloud.com/t/nextcloud-performance-optimizations-please-contribute/5136/10
    [mysqld]
    innodb_buffer_pool_size = 512M
    innodb_log_buffer_size = 32M