apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-pod
spec:
  selector:
    matchLabels:
      app: temp-pod
  template:
    metadata:
      labels:
        app: temp-pod
    spec:
      containers:
      - name: temp-pod
        image: ubuntu
        command:
          - sh
          - -c
          - tail -f /dev/null
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /nfs
            name: nfs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: temp-nfs-storage
      nodeSelector:
        kubernetes.io/hostname: anchorman
