apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-archiver
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-archiver
  template:
    metadata:
      labels:
        app: discord-archiver
    spec:
      containers:
      - name: discord-archiver
        image: docker.io/tyzbit/discord-archiver:1.7.0 # {"$imagepolicy": "flux-system:discord-archiver"}
        volumeMounts:
        - name: discord-archiver-config
          subPath: config.json
          mountPath: /config.json
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
      volumes:
      - name: discord-archiver-config
        secret:
          secretName: discord-archiver-config
      imagePullSecrets:
      - name: docker-hub
