apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-discord-amputator
  namespace: personal
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-discord-amputator
  template:
    metadata:
      labels:
        app: go-discord-amputator
    spec:
      containers:
      - name: go-discord-amputator
        image: docker.io/tyzbit/go-discord-amputator:1.4.0 # {"$imagepolicy": "flux-system:go-discord-amputator"}
        envFrom:
        - secretRef:
            name: go-discord-amputator
        livenessProbe: &probe
          failureThreshold: 3
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            port: 8080
            path: /healthcheck
        readinessProbe:
          !!merge <<: *probe
        startupProbe:
          !!merge <<: *probe
          failureThreshold: 15
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "256Mi"
      imagePullSecrets:
      - name: docker-hub
