apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-db-config
  namespace: personal
data:
  tuning.cnf: |
    # https://help.nextcloud.com/t/nextcloud-performance-optimizations-please-contribute/5136/10
    [mysqld]
    innodb_buffer_pool_size = 512M
    innodb_log_buffer_size = 32M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-cache-config
  namespace: personal
data:
  redis.conf: |
    unixsocket /tmp/redis/redis.sock
    unixsocketperm 777
    port 0
