apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: personal
spec:
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1 # active nas
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:23.0.8
          imagePullPolicy: Always
          # command: ["tail","-f","/dev/null"]
          envFrom:
            - secretRef:
                name: nextcloud-config
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: nextcloud-data
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 3Gi
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-nas
      imagePullSecrets:
        - name: docker-hub
      # nodeSelector:
      #   kubernetes.io/hostname: weatherman
