apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser
  namespace: media
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "40g"
    nginx.ingress.kubernetes.io/auth-url: "http://filebrowser-oauth2-proxy.media.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/target: ${blog_domain_ddns}
spec:
  tls:
    - hosts:
        - "files.${blog_domain}"
      secretName: files.${blog_domain}-tls
  rules:
  - host: files.${blog_domain}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: filebrowser
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-oauth2-proxy
  namespace: media
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - "files.${blog_domain}"
      secretName: files.${blog_domain}-tls
  rules:
  - host: files.${blog_domain}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: filebrowser-oauth2-proxy
            port:
              number: 80
