apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: frigate
  namespace: flux-system
namespace: home-automation
configMapGenerator:
  - name: frigate-config
    files:
      - config.yml=config.yaml
configurations:
  - kustomizeconfig.yaml
