apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-rpc-explorer
  namespace: crypto
  labels:
    app: btc-rpc-explorer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: btc-rpc-explorer
  template:
    metadata:
      annotations: {}
      labels:
        app: btc-rpc-explorer
    spec:
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - bitcoin
      #           - btc-rpc-explorer-cache
      #           - electrumx
      #       topologyKey: kubernetes.io/hostname
      containers:
        - name: btc-rpc-explorer
          image: tyzbit/btc-rpc-explorer:v3.1.1
          imagePullPolicy: Always
          env:
            - name: BTCEXP_HOST
              value: "0.0.0.0"
            - name: BTCEXP_ADDRESS_API
              value: electrumx
            - name: BTCEXP_NO_RATES
              value: "false"
            - name: BTCEXP_SLOW_DEVICE_MODE
              value: "false"
          envFrom:
            - secretRef:
                name: btc-rpc-explorer
          ports:
            - containerPort: 3002
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 512Mi
      imagePullSecrets:
        - name: docker-hub
