apiVersion: v1
kind: Service
metadata:
  name: youtube-dl
  namespace: default
spec:
  type: NodePort
  selector:
    app: youtube-dl
  ports:
    - name: http-youtube-dl
      protocol: TCP
      port: 80
      targetPort: 17442
