apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-secondary
  namespace: media
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "false"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/target: ${personal_domain_ddns}
spec:
  tls:
    - hosts:
        - "plex-backup.${blog_domain}"
      secretName: plex-backup.${blog_domain}-tls
  rules:
  - host: plex-backup.${blog_domain}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: plex-secondary
            port:
              number: 32400
