apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-incoming-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: default-qbittorrent
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.66
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: default-qbittorrent
    app.kubernetes.io/name: qbittorrent
  ports:
  - name: tcp
    protocol: TCP
    port: 32123
    targetPort: 32123
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-incoming-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: default-qbittorrent
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.66
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: default-qbittorrent
    app.kubernetes.io/name: qbittorrent
  ports:
  - name: udp
    protocol: UDP
    port: 32123
    targetPort: 32123
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-tracker
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.66
  selector:
    app.kubernetes.io/instance: default-qbittorrent
    app.kubernetes.io/name: qbittorrent
  ports:
  - name: tcp
    protocol: TCP
    port: 34543
    targetPort: 34543
