apiVersion: v1
kind: Service
metadata:
  name: project-zomboid
  namespace: games
spec:
  type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: project-zomboid-secondary
  ports:
    - port: 80
      protocol: TCP
      name: fb-http
      targetPort: 80
    - port: 27015
      protocol: TCP
      name: data1
      targetPort: 27015
    - port: 8766
      protocol: UDP
      name: data2
      targetPort: 8766
    - port: 8767
      protocol: UDP
      name: data3
      targetPort: 8767
    - port: 16261
      protocol: UDP
      name: data4
      targetPort: 16261
    - port: 16262
      protocol: UDP
      name: data5
      targetPort: 16262
