apiVersion: v1
kind: Service
metadata:
  name: project-zomboid-tcp
  namespace: games
  annotations:
    external-dns.alpha.kubernetes.io/hostname: projectzomboid.${blog_domain}
    external-dns.alpha.kubernetes.io/target: ${blog_domain_ddns}
    metallb.universe.tf/allow-shared-ip: games-project-zomboid-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.72
  externalTrafficPolicy: Local
  selector:
    app: project-zomboid
  ports:
    - port: 27015
      protocol: TCP
      name: data1
      targetPort: 27015
---
apiVersion: v1
kind: Service
metadata:
  name: project-zomboid-udp
  namespace: games
  annotations:
    metallb.universe.tf/allow-shared-ip: games-project-zomboid-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.72
  externalTrafficPolicy: Local
  selector:
    app: project-zomboid
  ports:
    - port: 8766
      protocol: UDP
      name: data2
      targetPort: 8766
    - port: 8767
      protocol: UDP
      name: data3
      targetPort: 8767
    - port: 16261
      protocol: UDP
      name: data4
      targetPort: 16261
    - port: 16262
      protocol: UDP
      name: data5
      targetPort: 16262
---
apiVersion: v1
kind: Service
metadata:
  name: project-zomboid-filebrowser
  namespace: games
spec:
  type: ClusterIP
  selector:
    app: project-zomboid
  ports:
    - port: 80
      protocol: TCP
      name: fb-http
      targetPort: 80
