apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: openttd-tdp
spec:
  type: LoadBalancer
  selector:
    app: openttd
  loadBalancerIP: 192.168.1.66
  ports:
  - name: main-tcp
    port: 3979
    protocol: TCP
    targetPort: 3979
  - name: alt-tcp
    protocol: TCP
    port: 3978
    targetPort: 3978
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: openttd-udp
spec:
  type: LoadBalancer
  selector:
    app: openttd
  loadBalancerIP: 192.168.1.66
  ports:
  - name: main-udp
    port: 3979
    protocol: UDP
    targetPort: 3979
  - name: alt-udp
    protocol: UDP
    port: 3978
    targetPort: 3978