apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-rpc-explorer
  namespace: crypto
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: btc-rpc-explorer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: btc-rpc-explorer
  template:
    metadata:
      annotations: {}
      labels:
        app: btc-rpc-explorer
    spec:
      containers:
        - name: btc-rpc-explorer
          image: tyzbit/btc-rpc-explorer:latest
          # image: tyzbit/btc-rpc-explorer:v3.1.1
          imagePullPolicy: Always
          env:
            - name: BTCEXP_HOST
              value: "0.0.0.0"
            - name: BTCEXP_ADDRESS_API
              value: electrumx
            - name: BTCEXP_NO_RATES
              value: "false"
            - name: BTCEXP_SLOW_DEVICE_MODE
              value: "false"
          envFrom:
            - secretRef:
                name: btc-rpc-explorer
          ports:
            - containerPort: 3002
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 512Mi
      imagePullSecrets:
        - name: docker-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-address-watcher
  namespace: crypto
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: btc-address-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-address-watcher
  template:
    metadata:
      labels:
        app: btc-address-watcher
    spec:
      containers:
        - name: btc-address-watcher
          image: bash
          imagePullPolicy: Always
          command:
          - bash
          - -c
          - |
            cp "/tmp/script.sh" /script.sh
            chmod +x /script.sh
            bash /script.sh
          env:
            - name: SLEEP
              value: "3600"
          envFrom:
            - name: btc-address-watcher
              secretRef:
                name: btc-address-watcher
          volumeMounts:
            - name: btc-address-watcher-config
              subPath: script.sh
              mountPath: /tmp/script.sh
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: btc-address-watcher-config
          configMap:
            name: btc-address-watcher
      imagePullSecrets:
        - name: docker-hub
