apiVersion: v1
kind: Service
metadata:
  name: electrumx
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: electrumx
  ports:
    - name: http-electrumx
      protocol: TCP
      port: 50002
      targetPort: 50002
