apiVersion: v1
kind: ConfigMap
metadata:
  name: default-backend-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>
    Access denied.
    </title>
    </head>
    <body>
    Access denied, pal.
    </body>
    </html>
