apiVersion: v1
kind: Service
metadata:
  name: duplicacy
spec:
  type: NodePort
  selector:
    app: duplicacy
  ports:
    - name: http-duplicacy
      protocol: TCP
      port: 80
      targetPort: 3875
